# 工作流名称
name: Sync-Images-to-DockerHub-Example
# 工作流运行时显示名称
run-name: ${{ github.actor }} is Sync Images to DockerHub.
# 怎样触发工作流
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# 工作流程任务（通常含有一个或多个步骤）
jobs:
  syncimages:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repos
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2.9.1

    - name: Login to Docker Hub
      uses: docker/login-action@v2.2.0
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        logout: false
        
    - name: Use Skopeo Tools Sync Image to Docker Hub
      run: |
        #!/usr/bin/env bash
        skopeo copy --all docker://quay.io/prometheus/alertmanager docker://pjzer0/monitoring-alertmanager
        skopeo copy --all docker://quay.io/prometheus/blackbox-exporter docker://pjzer0/monitoring-blackbox-exporter
        skopeo copy --all docker://quay.io/brancz/kube-rbac-proxy docker://pjzer0/monitoring-kube-rbac-proxy
        skopeo copy --all docker://grafana/grafana docker://pjzer0/monitoring-grafana
        skopeo copy --all docker://registry.k8s.io/kube-state-metrics/kube-state-metrics docker://pjzer0/monitoring-kube-state-metrics
        skopeo copy --all docker://quay.io/brancz/kube-rbac-proxy docker://pjzer0/monitoring-kube-rbac-proxy
        skopeo copy --all docker://quay.io/brancz/kube-rbac-proxy docker://pjzer0/monitoring-kube-rbac-proxy
        skopeo copy --all docker://quay.io/prometheus/node-exporter docker://pjzer0/monitoring-node-exporter
        skopeo copy --all docker://quay.io/brancz/kube-rbac-proxy docker://pjzer0/monitoring-kube-rbac-proxy
        skopeo copy --all docker://quay.io/prometheus/prometheus docker://pjzer0/monitoring-prometheus
        skopeo copy --all docker://registry.k8s.io/prometheus-adapter/prometheus-adapter docker://pjzer0/monitoring-prometheus-adapter
        skopeo copy --all docker://quay.io/prometheus-operator/prometheus-operator docker://pjzer0/monitoring-prometheus-operator
        skopeo copy --all docker://quay.io/brancz/kube-rbac-proxy docker://pjzer0/monitoring-kube-rbac-proxy

 
